### PR TITLE
Instrument ObjectInputStream.resolveClass instead of each Serializable class

### PR DESCRIPTION
**Pull request by eirbjo**
Instead of instrumenting each Serializable class, we instrument ObjectInputStream.resolveClass. This way we get one single hook into deserialization at a very early stage.

User code could potentially override resolveClass, but in that case, we might trust they know what they are doing?

If this is deemed to be a problem, we may want to instrument also subclasses of ObjectInputStream.

### CODE REVIEW

**Comment by eirbjo** [comment]
Instead of instrumenting subclasses, we could instead instrument the call site for resolveClass in ObjectInputStream.readNonProxyDesc. That way subclasses will get this for free since the enforcement point would always come before

**Comment by cgoudie** [comment]
+1

**Comment by cgoudie** [comment]
@eirbjo I really like the idea of ObjectInputStream.readNonProxyDesc since it protects everyone. +1

**Comment by cgoudie** [comment]
Does it also need to instrument readProxyDesc ?

**Comment by cgoudie** [comment]
My only concern with readNonProxyDesc is that this method is private and could change between java implementations.

**Comment by eirbjo** [comment]
How about we instrument every method in ObjectInputStream, injecting a call to the rejection checker just before any call to resolveClass?

**Comment by cgoudie** [comment]
If we want to go this much lower in the stack, ObjectStreamClass is required for this operation. This class is not final and a possible injection point, getName() is not final; however subclassing this class is not possible because the constructor is not visible.

This would be a way to inject a method that is definitely in a public API, but would impact every usage I can see. Thoughts?

**Comment by cgoudie** [comment]
I think this looks like 
1) rename getName() method to getNameInternal()
2) add a getName() method that calls getNameInternal() and checks the result before returning it, or throw exception.
3) Profit :D

**Comment by eirbjo** [comment]
ObjectInputStream.resolveClass is protected and as such it can only be called by ObjectInputStream (or subclasses). And ObjectInpuStream.readObject is final. 

So I don't think there is a way for a spec compliant implementation of ObjectInputStream not call resolveClass from a method in ObjectInputStream.

ObjectStreamClass.getName has uses besides deserialization which makes it unsafe to change. Serialization being one.

I'll implement the resolveClass call site instrumentation as mentioned and we'll see how that works.

**Comment by cgoudie** [comment]
+1

**Comment by eirbjo** [comment]
Ok, so now we instrument all call sites for resolveClass and add a static call to preventDeserialization/registerDeserialization just before the method call. 

Those methods now take and return ObjectStreamClass. This way the extra call does not change the stack and keeps the same maximum stack size.

@cgoudie WDYT?

**Comment by cgoudie** [comment]
Looking now

**Comment by cgoudie** [comment]
I'm not an ASM expert, but the change looks super simple, and as noted, I think this simplifies your overall code a lot. I really appreciate this change. I'll see if I can wind up some large scale testing with this branch.

**Comment by eirbjo** [comment]
Yes, this should localize the impact a lot since we're now only need to change the single class. This is perhaps a JDK feature asking to be implemented: Some sort of API where pre-deserialization checks like this could be injected. Maybe something like a static setClassVerifiers.

**Comment by bjorndarri** [comment]
I've been profiling a RMI client/server application with a whitelist (84 items) created by a dry-run and the performance impact seems to be minimal.

This is one elegant solution!

**Pull request merged**
